remote_theme: "mmistakes/minimal-mistakes@4.21.0"
minimal_mistakes_skin: "air"

#
# Relevant information
#

title: Floorplan for Home Assistant
subtitle: your imagination (almost) defines the limits
email: til@exeti.co
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for HA Floorplan, which are used in Home Assistant.
  Turn a dumb SVG-file into your new floorplan, and control devices,
  visualize states and much more. We're always doing our best to 
  support whatever you'd like to do. So, get started now - and please
  share your feedback!
baseurl: "/ha-floorplan"
url: "https://experiencelovelace.github.io" 
twitter_username: jekyllrb
github_username:  jekyll
repository: ExperienceLovelace/ha-floorplan

# Add head scripts with:
#head_scripts:
#  - https://code.jquery.com/jquery-3.2.1.min.js
#  - /assets/js/your-custom-head-script.js

# Add logo
#logo: "/assets/images/88x88.png"

permalink: /:categories/:title/
breadcrumbs: true  # disabled by default

show_date: true
search: true
search_full_content: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ExperienceLovelace/ha-floorplan"

#
# Build settings
#

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-archives

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
